[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.7.0"
dotenv = "0.15.0"
mysql = "25.0.1"
serde = {version = "1.0.203", features=["derive"]}
serde_json = "1.0.117"
